version: '3.5'
services:
  nginx:
    image: orleika/nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - $PWD/nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      - $PWD/nginx/conf.d:/etc/nginx/conf.d:ro
      - $PWD/www:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/cert:ro
      - $PWD/nginx/logs:/var/log/nginx
    links:
      - 'nodeapp'
  nodeapp:
    image: keymetrics/pm2:latest-alpine
    ports:
      - '3000:3000'
    volumes:
      - $PWD/nodeapp:/root
    working_dir: /root
    command: ['pm2-runtime', 'process.yml']
  api:
    image: wordnet-jp
    build:
      context: ./api
      cache_from:
        - python:3
    ports:
      - '5000:5000'
    volumes:
      - $PWD/api:/work
    command:
      - /bin/bash
    stdin_open: true
    tty: true
  mysql:
    image: mysql:5.7
    env_file:
      - .env
    volumes:
      - $PWD/mysql/conf.d:/etc/mysql/conf.d:ro
      - $PWD/mysql/initdb.d:/docker-entrypoint-initdb.d:ro
      - db-storage:/var/lib/mysql
    ports:
      - '3306:3306'
volumes:
  db-storage:
